In [10]:
%matplotlib inline

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
from scipy.stats import mode
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

In [11]:
df = pd.read_csv("df_DBSCAN.csv", skipinitialspace=True, sep=',')
df

PurchDate     Model  SubModel  VehYear  RefId  IsBadBuy  Auction  \
0      2009-07-28  1500 RAM   EXT CAB     2001  61608         1    ADESA   
1      2009-07-28  1500 RAM   EXT CAB     2001  61608         1    ADESA   
2      2009-02-25  1500 RAM  MEGA CAB     2006  50261         0  MANHEIM   
3      2009-01-12  1500 RAM  MEGA CAB     2006  33703         0  MANHEIM   
4      2009-01-12  1500 RAM  MEGA CAB     2006  33703         0  MANHEIM   
...           ...       ...       ...      ...    ...       ...      ...   
50901  2009-03-03    ZEPHYR     SEDAN     2006  32556         0  MANHEIM   
50902  2009-04-14    ZEPHYR     SEDAN     2006  33398         0  MANHEIM   
50903  2010-09-22    ZEPHYR     SEDAN     2006  42247         1    OTHER   
50904  2010-07-14    ZEPHYR     SEDAN     2006  70031         0    ADESA   
50905  2010-10-11    ZEPHYR     SEDAN     2006  64639         0    ADESA   

       VehicleAge     Make    Engine  ...  BYRNO VNZIP1  VNST  VehBCost  \
0               8    DODGE      5.2L  ...  23359  91752    CA    4315.0   
1               8    DODGE      5.2L  ...  23359  91752    CA    4315.0   
2               3    DODGE      5.7L  ...  19662  78219    TX   10835.0   
3               3    DODGE      5.7L  ...  19619  34761    FL   11515.0   
4               3    DODGE      5.7L  ...  19619  34761    FL   11515.0   
...           ...      ...       ...  ...    ...    ...   ...       ...   
50901           3  LINCOLN       NaN  ...   3453  80022    CO    9215.0   
50902           3  LINCOLN  3.0L SFI  ...   5546  34761    FL   10265.0   
50903           4  LINCOLN       NaN  ...  52492  27407    NC    9005.0   
50904           4  LINCOLN       NaN  ...  21053  85226    AZ    8615.0   
50905           4  LINCOLN       NaN  ...  21053  85226    AZ    8315.0   

      IsOnlineSale WarrantyCost Doors  TotalPrice  CostOverOdo  labels_DBSCAN  
0                0         1054    4D      5369.0     0.078288              0  
1                0         1054    4D      5369.0     0.078288              0  
2                0          920   NaN     11755.0     0.148980              0  
3                0          983   NaN     12498.0     0.142777              0  
4                0          983   NaN     12498.0     0.142777              0  
...            ...          ...   ...         ...          ...            ...  
50901            0         1118    4D     10333.0     0.133597              0  
50902            0         1118    4D     11383.0     0.150354              0  
50903            0         1272    4D     10277.0     0.124830              0  
50904            0         1272    4D      9887.0     0.121686              0  
50905            0         1272    4D      9587.0     0.113031              0  

[50906 rows x 31 columns]

In [12]:
dffinale = df

In [13]:
indexNames = df[df['labels_DBSCAN'] == -1 ].index
df.drop(indexNames , inplace=True)

In [14]:
columns_toAnalyze = ['VehicleAge', 'VehOdo', 'MMRAcquisitionAuctionAveragePrice', 'VehBCost', 'WarrantyCost', 'CostOverOdo']

df = df[columns_toAnalyze]

df.head()

VehicleAge  VehOdo  MMRAcquisitionAuctionAveragePrice  VehBCost  \
0           8   55117                             3192.0    4315.0   
1           8   55117                             3192.0    4315.0   
2           3   72728                            12423.0   10835.0   
3           3   80650                            13271.0   11515.0   
4           3   80650                            13271.0   11515.0   

   WarrantyCost  CostOverOdo  
0          1054     0.078288  
1          1054     0.078288  
2           920     0.148980  
3           983     0.142777  
4           983     0.142777

In [15]:
cluster = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='complete')  
cluster.fit_predict(df)
print("silhouette complete")
x = silhouette_score(df, cluster.labels_)
print(x)

silhouette complete
0.3663157958145133


In [16]:
np.unique(cluster.labels_, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=int64),
 array([ 1695, 23803, 13915, 10137,  1300], dtype=int64))

In [17]:
finale = cluster.labels_

In [18]:
dffinale['Label5complete'] = cluster.labels_

In [19]:
cluster = AgglomerativeClustering(n_clusters=4, affinity='euclidean', linkage='complete')  
cluster.fit_predict(df)
print("silhouette complete")
x = silhouette_score(df, cluster.labels_)
print(x)

silhouette complete
0.41676081367806145


In [20]:
np.unique(cluster.labels_, return_counts=True)

(array([0, 1, 2, 3], dtype=int64),
 array([15215, 23803,  1695, 10137], dtype=int64))

In [21]:
finale = cluster.labels_

In [22]:
dffinale['Label4complete'] = cluster.labels_

In [23]:
cluster = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='complete')  
cluster.fit_predict(df)
print("silhouette complete")
x = silhouette_score(df, cluster.labels_)
print(x)

silhouette complete
0.32735761130451196


In [24]:
np.unique(cluster.labels_, return_counts=True)

(array([0, 1, 2], dtype=int64), array([33940, 15215,  1695], dtype=int64))

In [25]:
finale = cluster.labels_

In [26]:
dffinale['Label3complete'] = cluster.labels_

In [27]:
cluster = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')  
cluster.fit_predict(df)
print("silhouette complete")
x = silhouette_score(df, cluster.labels_)
print(x)

silhouette complete
0.3385657938519316


In [28]:
np.unique(cluster.labels_, return_counts=True)

(array([0, 1, 2, 3, 4], dtype=int64),
 array([16666,  8818, 11018,  3585, 10763], dtype=int64))

In [29]:
finale = cluster.labels_

In [30]:
dffinale['Label5ward'] = cluster.labels_

In [31]:
cluster = AgglomerativeClustering(n_clusters=6, affinity='euclidean', linkage='ward')  
cluster.fit_predict(df)
print("silhouette complete")
x = silhouette_score(df, cluster.labels_)
print(x)

silhouette complete
0.33181685672908107


In [32]:
np.unique(cluster.labels_, return_counts=True)

(array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([ 8818, 13062, 11018,  3585, 10763,  3604], dtype=int64))

In [33]:
finale = cluster.labels_

In [34]:
dffinale['Label6ward'] = cluster.labels_

In [35]:
dffinale.to_csv(path_or_buf='AnalisiHierarchical.csv' ,index=False)